// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFile(arg1:number):Promise<void>;

export function OpenFolder(arg1:number):Promise<void>;

export function Reindex():Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<main.SearchResult>;

export function Stats():Promise<main.StatsResult>;
